baseURL = "https://www.webosose.org"
title = "webOS Open Source Edition"

enableRobotsTXT = true

contentDir = "content/en"

disableKinds = ["taxonomy", "taxonomyTerm"]

# Syntax Highlighting
pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsUseClasses = false
# See https://xyproto.github.io/splash/docs/longer/all.html
pygmentsStyle = "friendly"

[blackfriday]
smartypants = true

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML" ]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = -130

  [[menu.main]]
    identifier = "docs"
    name = "docs"
    url = "/docs/"
    weight = -120

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = -110

  [[menu.main]]
    identifier = "community"
    name = "community"
    url = "/community/"
    weight = -100

[params]
time_format = "January 02, 2006"
